### ISSUE TITLE
Can't compile dependency mongodb

### ISSUE THREAD

**Issue by MarkPare** [elixir-mongo/mongodb#241] opened 2018-10-20 19:25 UTC
I have a phoenix app that I'm trying to use with mongodb. When I try to start the app or run `mix deps.compile`, I get the following error:

```
== Compilation error in file lib/mongo/protocol.ex ==
** (CompileError) lib/mongo/protocol.ex: internal error in beam_record;
crash reason: {case_clause,{'EXIT',{{badmatch,false},
                      [{beam_utils,defs_list,4,
                                   [{file,"beam_utils.erl"},{line,1251}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1109}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1158}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1167}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1158}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1184}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1110}]},
                       {beam_utils,defs,3,
                                   [{file,"beam_utils.erl"},{line,1184}]}]}}}

  in function  compile:'-select_passes/2-anonymous-2-'/3 (compile.erl, line 585)
  in call from compile:'-internal_comp/5-anonymous-1-'/3 (compile.erl, line 349)
  in call from compile:fold_comp/4 (compile.erl, line 376)
  in call from compile:internal_comp/5 (compile.erl, line 360)
  in call from compile:'-do_compile/2-anonymous-0-'/2 (compile.erl, line 177)
  in call from compile:'-do_compile/2-anonymous-1-'/1 (compile.erl, line 190)
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
could not compile dependency :mongodb, "mix compile" failed. You can recompile this dependency with "mix deps.compile mongodb", update it with "mix deps.update mongodb" or clean it with "mix deps.clean mongodb
```

Running the commands suggested by the output does not address the issue.

My Elixir version:  `1.7.2`

Here's my `mix.exs` file:

```
defmodule MyApp.Mixfile do
  use Mix.Project

  def project do
    [
      app: :my_app,
      version: "0.0.1",
      elixir: ">= 1.5.3",
      elixirc_paths: elixirc_paths(Mix.env),
      compilers: [:phoenix, :gettext] ++ Mix.compilers,
      build_embedded: Mix.env == :prod,
      start_permanent: Mix.env == :prod,
      aliases: aliases(),
      deps: deps()
    ]
  end

  # Configuration for the OTP application.
  #
  # Type `mix help compile.app` for more information.
  def application do
    [
      mod: {MyApp.Application, []},
      extra_applications: [
        :logger, 
        :runtime_tools,
        :comeonin,
        :timex,
        :faker,
        :poolboy,
        :mongodb,
        :uuid,
        :httpoison,
      ]
    ]
  end

  # Specifies which paths to compile per environment.
  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_),     do: ["lib"]

  # Specifies your project dependencies.
  #
  # Type `mix help deps` for examples and options.
  defp deps do
    [
      {:phoenix, "~> 1.3.4"},
      {:phoenix_pubsub, "~> 1.0.2"},
      {:phoenix_ecto, "~> 3.3"},
      {:postgrex, "~> 0.13.5"},
      {:phoenix_html, "~> 2.12.0"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.11"},
      {:faker, "~> 0.10"},
      {:comeonin, "~> 4.1.1"},
      {:bcrypt_elixir, "~> 1.0.9"},
      {:cors_plug, "~> 1.5"},
      {:guardian, "~> 1.1"},
      {:timex, "~> 3.3"},
      {:timex_ecto, "~> 3.3"},
      {:tzdata, "~> 0.5.17"},
      {:cowboy, "~> 1.0"},
      {:mongodb, ">= 0.0.0"},
      {:poolboy, ">= 0.0.0"},
      {:uuid, "~> 1.1" },
      {:httpoison, "~> 1.2", override: true},
    ]
  end

  # Aliases are shortcuts or tasks specific to the current project.
  # For example, to create, migrate and run the seeds file at once:
  #
  #     $ mix ecto.setup
  #
  # See the documentation for `Mix` for more info on aliases.
  defp aliases do
    [
      "ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"],
      "ecto.reset": ["ecto.drop", "ecto.setup"],
      "test": ["ecto.create --quiet", "ecto.migrate", "test"]
    ]
  end
end
```

Any suggestions are appreciated!

**Comment by ankhers** [comment] 2018-10-20 20:14
Duplicate of #234. You will need to upgrade upgrade your OTP version.

**Closed as completed by ankhers** 2018-10-20 20:14 UTC
